---
title: "NY_data_analyzing"
author: "Yuxuan Chen"
output: 
  html_document:
      toc: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(viridis)
library(plotly)
library(dplyr)
library(readr)
library(maps)
library(choroplethr)
library(choroplethrMaps)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 9, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
drug_overdose = read_csv("./data/VSRR_Provisional_Drug_Overdose_Death_Counts.csv") %>% 
  janitor::clean_names()

state_level = c(state.name[1:8], "District of Columbia", state.name[9:32],"New York City", state.name[33:50])

drug_overdose_52 = 
  drug_overdose %>% 
  filter(!(state_name %in% c("United States"))) %>% 
  relocate(state_name) %>% 
  mutate(month = factor(month, levels = month.name), # change month and year to factor
         year = factor(year),
         state_name = factor(state_name, levels = state_level)) %>% 
  arrange(state_name) %>% 
  group_by(state_name, year) %>% 
  mutate(month = sort(month)) 
```

**Above are same as in `data_cleaning`, delete later.**


```{r}
nyc_df = 
  drug_overdose_52 %>%
  filter(state_name == "New York City")
```

1. By drug type

**missing drug type data in year: 2016, 2017** 
```{r}
nyc_df %>% 
  ungroup() %>% 
  filter(year %in% c("2016","2017")) %>% 
  select(year, month, indicator, data_value, predicted_value)
```

```{r}
summarize_nyc_drug = 
  nyc_df %>% 
  ungroup() %>% 
  select(year, month, indicator, data_value) %>% 
  filter(!(indicator %in% c("Number of Deaths","Number of Drug Overdose Deaths","Percent with drugs specified"))) %>%
  filter(!(year %in% c("2016","2017"))) %>% 
  mutate(indicator = as.factor(indicator)) %>% 
  mutate(
    indicator = fct_reorder(indicator, data_value)
  ) 
```

```{r}
summarize_nyc_drug %>% 
  summarize(n = sum(data_value)) %>% 
  arrange(desc(n))

summarize_nyc_drug %>% 
  ggplot(aes(x = indicator, y = data_value, fill = indicator)) +
  geom_violin(alpha = 0.5) +
  scale_x_discrete(labels = c("Psychostimulants \n with abuse potential \n (T43.6)", "Methadone \n (T40.3)", "Natural & \n semi-synthetic  \n opioids \n (T40.2)", "Natural & semi-\n synthetic opioids, \n incl. methadone \n (T40.2, T40.3)", "Heroin \n (T40.1)", "Cocaine \n (T40.5)", "Synthetic opioids, \n excl. \n methadone \n (T40.4)", "Natural, \n semi-synthetic, & \n synthetic opioids, \n incl. methadone \n (T40.2-T40.4)", "Opioids \n (T40.0-T40.4,\n T40.6)")) +
  guides(fill = guide_legend(nrow = 6, byrow = TRUE)) +
  labs(
    title = "NYC Number of Drug Overdose Deaths with Drug Categories (2015 - 2021)",
    x = "Drug Categories",
    y = "Number of Drug Overdose Deaths",
    caption = "Data comes from VSRR_Provisional_Drug_Overdose_Death_Counts dataset."
  )
```

2. percent of drug overdoes deaths over the total number of deaths by year in NYC:

```{r}
nyc_drug_overdose_death_df =
  nyc_df %>% 
  ungroup() %>% 
  select(year, month, indicator, data_value) %>% 
  filter(indicator %in% c("Number of Deaths", "Number of Drug Overdose Deaths")) %>% 
  pivot_wider(
    names_from = indicator,
    values_from = data_value
  ) %>% 
  janitor::clean_names() %>% 
  group_by(year, month) %>% 
  mutate(
    percent_overdose_death = number_of_drug_overdose_deaths / number_of_deaths
  )

nyc_drug_overdose_death_df %>%
  ungroup() %>% 
  ggplot(aes(x = month, y = percent_overdose_death, color = year)) +
  geom_point() +
  geom_line(aes(group = year)) +
  labs(
    title = "Percent of Drug Overdoes Deaths over Total Number of Deaths by Year in NYC",
    x = "Months",
    y = "Percent of Drug Overdoes Deaths",
    caption = "Data comes from VSRR_Provisional_Drug_Overdose_Death_Counts dataset from 2015 to 2021)."
  )

```

```{r}
nyc_drug_overdose_death_df %>%
  ungroup() %>% 
  ggplot(aes(x = month, y = percent_overdose_death, group = NA)) +
  geom_point() +
  geom_line() +
  facet_grid(.~ year) +
  labs(
    title = "Percent of Drug Overdoes Deaths over Total Number of Deaths by Year in NYC",
    x = "Months",
    y = "Percent of Drug Overdoes Deaths",
    caption = "Data comes from VSRR_Provisional_Drug_Overdose_Death_Counts dataset from 2015 to 2021."
  ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

```

3. By drug by year

```{r}
summarize_nyc_drug %>% 
  ggplot(aes(x = year, y = data_value, color = indicator)) +
  geom_point() +
  geom_line(aes(group = indicator)) +
  scale_color_viridis(discrete = TRUE, labels = c("Psychostimulants with abuse potential (T43.6)", "Methadone (T40.3)", "Natural & semi-synthetic opioids (T40.2)", "Natural & semi-synthetic opioids, incl. methadone (T40.2, T40.3)", "Heroin (T40.1)", "Cocaine (T40.5)", "Synthetic opioids, excl. methadone (T40.4)", "Natural, semi-synthetic, & synthetic opioids, incl. methadone (T40.2-T40.4)", "Opioids (T40.0-T40.4,T40.6)")) +
  guides(color = guide_legend(nrow = 6, byrow = TRUE)) +
  labs(
    title = "Number of Drug Overdose Deaths with Drug Categories by Year in NYC",
    x = "Drug Categories",
    y = "Number of Drug Overdose Deaths",
    caption = "Data comes from VSRR_Provisional_Drug_Overdose_Death_Counts dataset between 2015 and 2021."
  )
```

3. Median Household Income

```{r}
income_df = 
  read_csv("./data/median_household_income_ny.csv") %>% 
  janitor::clean_names() %>% 
  select(year, household_income_by_race, household_income_by_race_moe, geography) %>% 
  filter(
    geography %in% c("New York, NY", "United States"),
    year >= "2015") %>% 
  mutate(
    geography = str_replace(geography, ", NY", "")) 

income_df %>% 
  mutate(text_label = str_c("Year: ", year, "\nMedian Household Income: $", household_income_by_race, 
                            "\nMargin of error: ± $", household_income_by_race_moe)) %>% 
  plot_ly(
    x = ~year, y = ~household_income_by_race, color = ~geography, text = ~text_label, 
    alpha = 0.5, type = "scatter", mode = "markers+lines", colors = "viridis") %>% 
  layout(
    title = "Median Household Income: New York vs. The U.S",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Median Household Income"))
  
```


4. Map by county:
leeeeeet's see.....
```{r, eval = FALSE}
data(county.fips)
abc = county.fips %>% 
  filter(str_detect(polyname, "new york,bronx|,new york|queens|new york,kings|new york,richmond")) %>% 
  separate(polyname, into = c("state", "county"), sep = "\\,") %>% 
  select(-state) %>% 
  as.tibble() %>% 
  mutate(value = c(100,300,500,300,200)) %>% 
  rename(region = fips,
         value = value) %>% 
  select(-county)  # number made up
d = abc %>% 
  select(region)
county_choropleth(abc, county_zoom = d$region)
```
```{r}
data(county.regions)
nyc_county_names = c("kings", "bronx", "new york", "queens", "richmond")
nyc_county_fips = county.regions %>%
  filter(state.name == "new york" & county.name %in% nyc_county_names) %>%
  select(region)
county_choropleth(df_pop_county, 
                  title        = "Population of Counties in New York City",
                  legend       = "Population",
                  county_zoom = nyc_county_fips$region)

```




**Percent with drugs specified	for each month from 2015-2021 are high enough, all above 98%**

```{r}
drug_percent_specified = 
  nyc_df %>%
  ungroup() %>% 
  select(year, month, indicator, data_value) %>% 
  filter(indicator == "Percent with drugs specified")
```


